export enum SeatStatus {
  FREE = 'FREE',
  RESERVED = 'RESERVED',
  OCCUPIED = 'OCCUPIED',
  ENDING_SOON = 'ENDING_SOON',
  PENDING_RELEASE = 'PENDING_RELEASE'
}

export enum DeviceOnlineStatus {
  ONLINE = 'ONLINE',
  OFFLINE = 'OFFLINE'
}

export enum SeatAvailability {
  AVAILABLE = 'AVAILABLE',
  UNAVAILABLE = 'UNAVAILABLE'
}

export enum SeatUnavailableReason {
  DEVICE_OFFLINE = 'DEVICE_OFFLINE',
  SENSOR_ERROR = 'SENSOR_ERROR',
  ADMIN_MAINTENANCE = 'ADMIN_MAINTENANCE'
}

export enum ReservationStatus {
  WAITING_CHECKIN = 'WAITING_CHECKIN',
  CHECKED_IN = 'CHECKED_IN',
  FINISHED = 'FINISHED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  USER_RELEASED = 'USER_RELEASED',
  ADMIN_RELEASED = 'ADMIN_RELEASED',
  TIMEOUT_FINISHED = 'TIMEOUT_FINISHED'
}

export enum PresenceStatus {
  PRESENT = 'PRESENT',
  ABSENT = 'ABSENT',
  UNKNOWN = 'UNKNOWN',
  ERROR = 'ERROR'
}
