ALTER TYPE "AnomalyStatus" ADD VALUE 'ACKNOWLEDGED';
ALTER TYPE "AnomalyStatus" ADD VALUE 'CLOSED';

ALTER TYPE "AdminActionType" ADD VALUE 'ACKNOWLEDGE_ANOMALY';
ALTER TYPE "AdminActionType" ADD VALUE 'CLOSE_ANOMALY';
